### ISSUE TITLE
Erroneous "There was an error downloading Kano OS.."

### ISSUE THREAD

**Issue by ishotjr** [KanoComputing/kano-burners#27]
Kano OS burner reports "There was an error downloading Kano OS.." despite working internet connection.

### Steps to Repro
1. Download http://80.243.184.98/public/burners/kano-burner-osx.zip from http://www.kano.me/downloads
1. Unzip
1. Launch
1. Select device
1. Burn
1. :heavy_check_mark: "I still want to do this"
1. Click "OK"
1. Observe error message despite working internet connection:

![screenshot 2014-12-20 13 32 55](https://cloud.githubusercontent.com/assets/1594827/5515871/a2f50f38-884d-11e4-9ef8-f14a9c7470f3.png)

This is on a MacBook Air running OS X 10.9.1. :bowtie:

**Comment by ctceismc** [comment]
Having the same problem today.

**Comment by pazdera** [comment]
Hi @ctceismc, it was the same metadata file missing problem all over again. It should be back up and working. I'm sorry about that.

Thanks for letting us know!

**Comment by philiptevans** [comment]
I'm having the same problem

**Comment by radujipa** [comment]
Currently the downloading seems to fail at [common/download.py#L128](https://github.com/KanoComputing/kano-burners/blob/master/src/common/download.py#L128).

Looking at http://downloads.kano.me/public/ it seems that 
`Kanux-Beta-v1.3.2-release.img.json` should actually be renamed to 
`Kanux-Beta-v1.3.2-release.img.gz.json`

Perhaps what @pazdera was referring to :)

**Comment by alexnklein** [comment]
Radu, lovely to see you again

An evening project, to fix the Burners, name your price – email me alex@kano.me if you’re interested….

**Comment by x-du** [comment]
Having the problem today.

**Comment by tombettany** [comment]
Given that there is currently a problem with the downloading, it might be an opportunity to incorporate https://github.com/KanoComputing/kano-burners/pull/25 which proposes a new, simpler (and easier to maintain) convention for the contents of `latest.json`.

**Comment by gerito1** [comment]
The problem is still present.
src/common/download still fails
![sin titulo2](https://cloud.githubusercontent.com/assets/2503482/6034155/2cdc30ea-abfe-11e4-8a91-e8fa7f83c3a7.jpg)
Kano-burner is attempting to download
http://downloads.kano.me/Kanux-Beta-v1.3.2-release.img.json
Instead of http: //downloads.kano.me/**public/**Kanux-Beta-v1.3.2-release.img.json

**Comment by gerito1** [comment]
Also the filename reported in os_info and returned by downloading should include the extension ".gz".
Or perhaps the burner should assume that, and append it itself.

**Comment by tombettany** [comment]
@gerito1 You are absolutely right, I've updated https://github.com/KanoComputing/kano-burners/issues/34 and we'll get the `public/` appended to `base_url`.

I'm a little confused about the `.gz` problem - don't we append it [here](https://github.com/KanoComputing/kano-burners/blob/master/src/common/download.py#L131) and then use it [here](https://github.com/KanoComputing/kano-burners/blob/master/src/common/download.py#L149)?

**Comment by gerito1** [comment]
You are right, sorry. Nevermind me.

**Comment by gerito1** [comment]
@tombettany It's me again.
In the burn.py, we are using 7zip to decompress the image and pipe it to dd. (We do not extract the file and then burn it, we burn the image while decompressing).
The filename is for the "Kanux-***.img" the image, but because we don't want to create a 2GB file (or more) it would be nice that the name of the compressed file downloaded by the downloader should be reported in os_info. That's what I mean.
Something like "compresed_filename" = "Kanux-***.img.gz" or "Kanux-***.img.zip" etc, if 7zip support it the burner should't care what the fietype downloaded.

**Comment by gerito1** [comment]
@tombettany Check my last commit https://github.com/KanoComputing/kano-burners/pull/33
I'm moddifying the structure of "os_info" to add the compressed filename.
Check if is reasonable please.
I'm accepting suggestions. Thanks.

**Comment by Ealdwulf** [comment]
@alex5imon It looks like the underlying problem with this one was fixed, I think it can be closed.
